### ISSUE TITLE
Помилка розгортання

### ISSUE THREAD

**Issue by Renorder** [pupenasan/pacframework-tools#1]
Вітаю.
Під час застосування розгортання змінних для імпорту у Unity PRO виникла наступна помилка:
![err](https://user-images.githubusercontent.com/61793962/164443380-3dd631c6-34c3-4dd6-9371-1b1862dadc48.png)

Після видалення утиліти і її повторного інсталяції звернув увагу, що установка пройшла не вдало:
![err2](https://user-images.githubusercontent.com/61793962/164444595-f79b9f4f-690d-4363-a450-07068b7819c6.png)
При цьому більшість файлів встановлені.
Повторна спроба розгорнути змінні завершилась тією ж помилкою як і до цього.
Також спробував перевстановити з Node.js 18.0.0 версії, безрезультатно.
Можливо ви знаєте, що саме може заважати інсталяції або як це визначити?

**Comment by pupenasan** [comment]
Повторна інсталяція запускається вже з наявною робочою папкою, тому при запуску `index` видає таке повідомлення. Уже змінив на повідомлення `Робоча директорія вже була проініціалізована до цього!`
З помилкою використання вже почав займатися.

**Comment by pupenasan** [comment]
До речі @Renorder яка команда була запущена (можна тикнути в завдання з методички як що)

**Comment by pupenasan** [comment]
виправив баги, дякую @Renorder за зауваження. Зробіть наступне:
- [ ] обновіться до нової версії
```
cd C:\pacframeworktools
npm install pacframework-tools@latest
```
- [ ] завантажте нову версію Excel файлу мастерданих
- [ ] запустіть процедуру розгортання 
`node C:\pacfwtools\node_modules\pacframework-tools\index seuncreateall`

**Comment by Renorder** [comment]
Супер!
Файли успішно створені, нормально імпортуються, все працює.
Дякую)
